/**
 * @fileoverview gRPC-Web generated client stub for helloworld
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: helloworld.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb';
import * as helloworld_pb from './helloworld_pb';


export class GreeterClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSayHello = new grpcWeb.MethodDescriptor(
    '/helloworld.Greeter/SayHello',
    grpcWeb.MethodType.UNARY,
    helloworld_pb.HelloRequest,
    helloworld_pb.HelloReply,
    (request: helloworld_pb.HelloRequest) => {
      return request.serializeBinary();
    },
    helloworld_pb.HelloReply.deserializeBinary
  );

  sayHello(
    request: helloworld_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null): Promise<helloworld_pb.HelloReply>;

  sayHello(
    request: helloworld_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: helloworld_pb.HelloReply) => void): grpcWeb.ClientReadableStream<helloworld_pb.HelloReply>;

  sayHello(
    request: helloworld_pb.HelloRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: helloworld_pb.HelloReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/helloworld.Greeter/SayHello',
        request,
        metadata || {},
        this.methodDescriptorSayHello,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/helloworld.Greeter/SayHello',
    request,
    metadata || {},
    this.methodDescriptorSayHello);
  }

}

export class MessangerClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetMessages = new grpcWeb.MethodDescriptor(
    '/helloworld.Messanger/GetMessages',
    grpcWeb.MethodType.SERVER_STREAMING,
    google_protobuf_empty_pb.Empty,
    helloworld_pb.MessageResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    helloworld_pb.MessageResponse.deserializeBinary
  );

  getMessages(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<helloworld_pb.MessageResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/helloworld.Messanger/GetMessages',
      request,
      metadata || {},
      this.methodDescriptorGetMessages);
  }

  methodDescriptorCreateMessage = new grpcWeb.MethodDescriptor(
    '/helloworld.Messanger/CreateMessage',
    grpcWeb.MethodType.UNARY,
    helloworld_pb.MessageRequest,
    helloworld_pb.MessageResponse,
    (request: helloworld_pb.MessageRequest) => {
      return request.serializeBinary();
    },
    helloworld_pb.MessageResponse.deserializeBinary
  );

  createMessage(
    request: helloworld_pb.MessageRequest,
    metadata: grpcWeb.Metadata | null): Promise<helloworld_pb.MessageResponse>;

  createMessage(
    request: helloworld_pb.MessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: helloworld_pb.MessageResponse) => void): grpcWeb.ClientReadableStream<helloworld_pb.MessageResponse>;

  createMessage(
    request: helloworld_pb.MessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: helloworld_pb.MessageResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/helloworld.Messanger/CreateMessage',
        request,
        metadata || {},
        this.methodDescriptorCreateMessage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/helloworld.Messanger/CreateMessage',
    request,
    metadata || {},
    this.methodDescriptorCreateMessage);
  }

}

